# Generated by Django 4.2.28 on 2026-02-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tareas", "0002_incidencia"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incidencia",
            old_name="titulo",
            new_name="asunto",
        ),
        migrations.RemoveField(
            model_name="incidencia",
            name="resuelta",
        ),
        migrations.AddField(
            model_name="incidencia",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("tecnico", "Soporte Técnico"),
                    ("facturacion", "Facturación"),
                    ("acceso", "Problema de acceso"),
                ],
                default="tecnico",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="incidencia",
            name="prioridad",
            field=models.CharField(
                choices=[("baja", "Baja"), ("media", "Media"), ("alta", "Alta")],
                default="media",
                max_length=20,
            ),
        ),
    ]
