# Generated by Django 4.2.28 on 2026-02-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tareas", "0003_rename_titulo_incidencia_asunto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidencia",
            name="archivo",
            field=models.FileField(blank=True, null=True, upload_to="incidencias/"),
        ),
        migrations.AddField(
            model_name="incidencia",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("proceso", "En proceso"),
                    ("cerrada", "Cerrada"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
